/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import controle.controleCliente;
import dao.ClienteDAO;
import entidade.Cliente;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pc05
 */
public class ListaCliente extends javax.swing.JDialog {

    /**
     * Creates new form ListaCliente
     */
    
    Cliente cliente;
    public ListaCliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public ListaCliente(java.awt.Frame parent, boolean modal,Cliente cliente) {
        super(parent, modal);
        initComponents();
         this.cliente = cliente;
        listarClientes();
        
    }
    
    private void listarClientes() {
        try {
            //setar para tabela modelo de dados
            tbListagemCliente.setModel(this.obterDadosParaTabelaCompleto());
            tbListagemCliente.getColumnModel().getColumn(0).setPreferredWidth(1);
            tbListagemCliente.getColumnModel().getColumn(1).setPreferredWidth(170);
            tbListagemCliente.getColumnModel().getColumn(2).setPreferredWidth(100);
            tbListagemCliente.getColumnModel().getColumn(3).setPreferredWidth(80);
            tbListagemCliente.getColumnModel().getColumn(4).setPreferredWidth(170);
            tbListagemCliente.getColumnModel().getColumn(5).setPreferredWidth(35);
            

        } catch (Exception ex) {
//            Logger.getLogger(tbListagemCliente.class.getName()).log(Level.SEVERE, null, ex);
System.out.println("Erro ao fazer a consulta "+ ex);
        }
    }
     
      private DefaultTableModel obterDadosParaTabelaCompleto() throws Exception {
        DefaultTableModel dtm = new DefaultTableModel() {
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
//adiciona titulo para as colunas

//         

          controleCliente controlCliente = new controleCliente();
          
          
//        Cliente cliente = new Cliente();Cliente cliente
        ClienteDAO clienteDAO = new ClienteDAO();
        ArrayList<Cliente> clienteArray = clienteDAO.consultarCliente(cliente);

        dtm.addColumn("ID");
        dtm.addColumn("NOME");
        dtm.addColumn("SOBRENOME");
        dtm.addColumn("CPF");
        dtm.addColumn("RUA");
        dtm.addColumn("NUMERO");
       

        for (int i = 0; i < clienteArray.size(); i++) {
            //popular tabela
            
            dtm.addRow(new String[]{String.valueOf(clienteArray.get(i).getId()),
                clienteArray.get(i).getNome(),
                clienteArray.get(i).getSobrenome(),
                clienteArray.get(i).getCfp(),
                clienteArray.get(i).getRua(),
                String.valueOf(clienteArray.get(i).getNumeroRua()),
                
            });
        }
//retorna o modelo
        return dtm;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbListagemCliente = new javax.swing.JTable();
        btSelecionar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tbListagemCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbListagemCliente);

        btSelecionar.setText("selecionar");
        btSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSelecionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 983, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btSelecionar)
                .addGap(144, 144, 144))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btSelecionar)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSelecionarActionPerformed

        cadastroCliente cadastroCliente = new cadastroCliente();
        int row = tbListagemCliente.getSelectedRow();
        cliente.setId(Integer.parseInt(tbListagemCliente.getValueAt(row, 0).toString()));
        cliente.setNome(tbListagemCliente.getValueAt(row, 1).toString());
        cliente.setSobrenome(tbListagemCliente.getValueAt(row, 2).toString());
        cliente.setCfp(tbListagemCliente.getValueAt(row, 3).toString());
        cliente.setRua(tbListagemCliente.getValueAt(row, 4).toString());
        cliente.setNumeroRua(Integer.parseInt(tbListagemCliente.getValueAt(row, 5).toString()));

        this.setVisible(false);
    }//GEN-LAST:event_btSelecionarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ListaCliente dialog = new ListaCliente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSelecionar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbListagemCliente;
    // End of variables declaration//GEN-END:variables
}
